"""Rules-based research ideas from your portfolio and the market data in the lake.

Every idea is produced by a fixed, documented rule and carries the numbers that triggered it, so
you can check the reasoning instead of trusting a black box. These are prompts for your own
research, not recommendations: the bot proposes, you decide, and nothing here places orders.

Rules (thresholds in ``Limits``):

Holdings
- **Trend broken**: a held name closed its last full month below its 10-month average (strategy
  1 would hold cash instead).
- **Deep drawdown**: a held name is more than 25% below its 52-week high.
- **Covered-call eligible**: 100+ shares of an optionable name (informational).

Portfolio
- **Position over cap**: any single stock above 10% of the portfolio (the plan's risk limit;
  diversified funds are exempt).
- **Sector over cap**: any sector above 30%.
- **Narrow asset mix**: more than 80% in US equity, nothing in bonds or international.
- **High beta**: current holdings move more than 1.2x the S&P 500.
- **Analytics coverage**: share of the portfolio we cannot price (mutual funds, options).

Strategies
- **MA-timing overlay**: strategy 1 applied to your current mix; suggested when it would have
  cut the max drawdown materially without giving up much return.
- **GTAA diversifier**: Faber's 5-asset portfolio, suggested when the mix is mostly US equity.

Candidates (names you don't hold, from the bars universe)
- In an uptrend (above the 10-month average) with positive 12-1 momentum, ranked by momentum,
  low correlation to your portfolio, and filling a sector you're light in.
"""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass, field
from datetime import date
from typing import Any, Literal

import pandas as pd

from tp_core import metrics
from tp_core.bars import close_matrix, load_bars
from tp_core.portfolio import (
    CASH_KIND,
    Classifier,
    holdings_backtest,
    holdings_table,
    latest_snapshot,
    priced_weights,
)
from tp_core.storage import Lake
from tp_strategies.ma_timing import equal_weight_monthly, ma_timing, month_end_closes

Kind = Literal["holding", "portfolio", "strategy", "candidate"]
Severity = Literal["attention", "consider", "info"]

DISCLAIMER = (
    "Research ideas generated by fixed rules from historical prices and your holdings. "
    "Not investment advice; backtests are hypotheses, not evidence. You make every decision."
)
GTAA = ("SPY", "EFA", "IEF", "VNQ", "DBC")
OPTIONABLE_KINDS = frozenset({"stock", "etf", "adr"})
SINGLE_NAME_KINDS = frozenset({"stock", "adr"})


@dataclass(frozen=True)
class Limits:
    max_position: float = 0.10
    max_sector: float = 0.30
    max_us_equity: float = 0.80
    high_beta: float = 1.2
    deep_drawdown: float = 0.25
    overlay_min_dd_improvement: float = 0.05  # 5 percentage points of max drawdown
    overlay_max_cagr_cost: float = 0.02  # give up at most 2 points of CAGR
    candidates: int = 5
    min_history_days: int = 260


@dataclass(frozen=True)
class Idea:
    kind: Kind
    severity: Severity
    title: str
    summary: str
    rationale: list[str]
    symbols: list[str] = field(default_factory=list)
    score: float = 0.0
    metrics: dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True)
class IdeasReport:
    as_of: date | None
    ideas: list[Idea]
    signals: pd.DataFrame  # per-symbol trend/momentum table the ideas were built from
    disclaimer: str = DISCLAIMER

    def by_kind(self, kind: Kind) -> list[Idea]:
        return [i for i in self.ideas if i.kind == kind]

    def to_dict(self) -> dict[str, Any]:
        return {
            "as_of": self.as_of.isoformat() if self.as_of else None,
            "disclaimer": self.disclaimer,
            "ideas": [_clean_floats(asdict(i)) for i in self.ideas],
        }


def _clean_floats(obj: Any) -> Any:
    """NaN/inf are not valid JSON."""
    if isinstance(obj, float):
        return None if not math.isfinite(obj) else obj
    if isinstance(obj, dict):
        return {k: _clean_floats(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_clean_floats(v) for v in obj]
    return obj


# -- per-symbol signals -------------------------------------------------------------------------


def symbol_signals(prices: pd.DataFrame, months: int = 10) -> pd.DataFrame:
    """Trend and momentum facts per symbol from daily adjusted closes."""
    month_end = month_end_closes(prices)
    sma = month_end.rolling(months, min_periods=months).mean()
    rows = []
    for symbol in prices.columns:
        p = prices[symbol].dropna()
        if p.empty:
            continue
        last_me = month_end[symbol].dropna()
        last_sma = sma[symbol].dropna()
        above = (
            bool(last_me.iloc[-1] > last_sma.iloc[-1]) if len(last_sma) and len(last_me) else None
        )
        rets = p.pct_change(fill_method=None).dropna()
        momentum = float(p.iloc[-22] / p.iloc[-253] - 1) if len(p) >= 253 else math.nan
        vol = float(rets.iloc[-63:].std() * math.sqrt(252)) if len(rets) >= 63 else math.nan
        rows.append(
            {
                "symbol": symbol,
                "last_close": float(p.iloc[-1]),
                "history_days": len(p),
                "above_10m_sma": above,
                "sma_10m": float(last_sma.iloc[-1]) if len(last_sma) else math.nan,
                "month_end_close": float(last_me.iloc[-1]) if len(last_me) else math.nan,
                "momentum_12_1": momentum,
                "vol_63d": vol,
                "drawdown_52w": float(p.iloc[-1] / p.iloc[-252:].max() - 1),
            }
        )
    return pd.DataFrame(rows).set_index("symbol") if rows else pd.DataFrame()


# -- the engine ---------------------------------------------------------------------------------


def generate_ideas(
    table: pd.DataFrame,
    prices: pd.DataFrame,
    classifier: Classifier,
    *,
    limits: Limits | None = None,
) -> IdeasReport:
    """``table`` from ``tp_core.portfolio.holdings_table``; ``prices`` = adjusted closes (wide)."""
    limits = limits or Limits()
    signals = symbol_signals(prices)
    as_of = prices.index[-1].date() if len(prices) else None
    ideas: list[Idea] = []
    if not table.empty:
        ideas += _holding_ideas(table, signals, limits)
        ideas += _portfolio_ideas(table, prices, limits)
        ideas += _strategy_ideas(table, prices, limits)
    ideas += _candidate_ideas(table, prices, signals, classifier, limits)
    order = {"attention": 0, "consider": 1, "info": 2}
    ideas.sort(key=lambda i: (order[i.severity], -i.score))
    return IdeasReport(as_of=as_of, ideas=ideas, signals=signals)


def _holding_ideas(table: pd.DataFrame, signals: pd.DataFrame, limits: Limits) -> list[Idea]:
    ideas: list[Idea] = []
    by_symbol = {
        str(sym): {str(k): v for k, v in row.items()}
        for sym, row in signals.to_dict("index").items()
    }
    for _, row in table.iterrows():
        symbol = str(row["symbol"])
        if symbol not in by_symbol:
            continue
        s = by_symbol[symbol]
        weight = float(row["weight"])
        if _flag(s["above_10m_sma"]) is False:
            ideas.append(
                Idea(
                    kind="holding",
                    severity="attention",
                    title=f"{symbol}: trend broken",
                    summary=(
                        f"{symbol} closed its last full month below its 10-month average; "
                        "strategy 1 would be in cash for this name."
                    ),
                    rationale=[
                        f"Month-end close {s['month_end_close']:.2f} vs 10-month average "
                        f"{s['sma_10m']:.2f}",
                        f"{weight:.1%} of your portfolio",
                        f"12-1 momentum {s['momentum_12_1']:+.1%}"
                        if math.isfinite(s["momentum_12_1"])
                        else "Under a year of history",
                    ],
                    symbols=[symbol],
                    score=weight,
                    metrics={"weight": weight, "sma_10m": float(s["sma_10m"])},
                )
            )
        if s["drawdown_52w"] <= -limits.deep_drawdown:
            ideas.append(
                Idea(
                    kind="holding",
                    severity="consider",
                    title=f"{symbol}: {s['drawdown_52w']:.0%} below its 52-week high",
                    summary="A deep drawdown is a good moment to re-check the original thesis.",
                    rationale=[
                        f"Last close {s['last_close']:.2f}, {s['drawdown_52w']:.1%} from the "
                        "52-week high",
                        f"63-day volatility {s['vol_63d']:.0%} annualized",
                    ],
                    symbols=[symbol],
                    score=-float(s["drawdown_52w"]),
                    metrics={"drawdown_52w": float(s["drawdown_52w"])},
                )
            )
        if row["kind"] in OPTIONABLE_KINDS and float(row["quantity"] or 0) >= 100:
            ideas.append(
                Idea(
                    kind="holding",
                    severity="info",
                    title=f"{symbol}: covered-call eligible",
                    summary=(
                        f"You hold {row['quantity']:.0f} shares. Per the options playbook a "
                        "covered call fits when IV rank is above 50; IV-rank analytics come "
                        "with the options module."
                    ),
                    rationale=[f"{int(row['quantity'] // 100)} contract(s) of coverage"],
                    symbols=[symbol],
                )
            )
    return ideas


def _portfolio_ideas(table: pd.DataFrame, prices: pd.DataFrame, limits: Limits) -> list[Idea]:
    ideas: list[Idea] = []
    risky = table[table["kind"] != CASH_KIND]
    # The cap is about single-company risk: diversified funds (an S&P 500 index fund) are exempt.
    single_names = risky[risky["kind"].isin(SINGLE_NAME_KINDS)]
    for _, row in single_names[single_names["weight"] > limits.max_position].iterrows():
        ideas.append(
            Idea(
                kind="portfolio",
                severity="attention",
                title=f"{row['symbol']} is {row['weight']:.0%} of the portfolio",
                summary=(
                    f"Above the {limits.max_position:.0%} single-position cap in the risk plan; "
                    "one bad earnings report moves the whole account."
                ),
                rationale=[f"Market value {row['market_value']:,.0f}"],
                symbols=[str(row["symbol"])],
                score=float(row["weight"]),
                metrics={"weight": float(row["weight"])},
            )
        )
    sectors = risky.groupby("sector")["weight"].sum()
    for sector, weight in sectors[sectors > limits.max_sector].items():
        names = risky[risky["sector"] == sector].sort_values("weight", ascending=False)
        ideas.append(
            Idea(
                kind="portfolio",
                severity="consider",
                title=f"{sector} is {weight:.0%} of the portfolio",
                summary=f"Above the {limits.max_sector:.0%} sector cap in the risk plan.",
                rationale=[
                    "Largest: "
                    + ", ".join(
                        f"{s} {w:.0%}"
                        for s, w in list(zip(names["symbol"], names["weight"], strict=True))[:4]
                    )
                ],
                symbols=[str(s) for s in names["symbol"]],
                score=float(weight),
                metrics={"weight": float(weight)},
            )
        )
    classes = table.groupby("asset_class")["weight"].sum()
    us_eq = float(classes.get("US Equity", 0.0))
    diversifiers = ("US Treasuries", "US Bonds", "International Equity", "Gold", "Commodities")
    if us_eq > limits.max_us_equity and not any(classes.get(c, 0) > 0.02 for c in diversifiers):
        ideas.append(
            Idea(
                kind="portfolio",
                severity="consider",
                title=f"{us_eq:.0%} in US equity, little else",
                summary=(
                    "No meaningful bonds, international or real assets: returns ride on one "
                    "market. See the GTAA idea below for a rules-based diversifier."
                ),
                rationale=[
                    f"{c}: {w:.0%}" for c, w in classes.sort_values(ascending=False).items()
                ],
                score=us_eq,
                metrics={"us_equity": us_eq},
            )
        )
    weights = priced_weights(table, set(prices.columns))
    coverage = float(weights.sum())
    risky_weight = float(risky["weight"].sum())
    if risky_weight - coverage > 0.05 + 1e-9:  # tolerance: 5% exactly is not "more than 5%"
        unpriced = risky[~risky["symbol"].isin(weights.index)]
        ideas.append(
            Idea(
                kind="portfolio",
                severity="info",
                title=f"{risky_weight - coverage:.0%} of the portfolio isn't price-analysed",
                summary=(
                    "Mutual funds and options aren't in the market-data feed, so beta, trend and "
                    "backtests below cover only the rest."
                ),
                rationale=[", ".join(str(s) for s in unpriced["symbol"].head(8))],
                symbols=[str(s) for s in unpriced["symbol"]],
                metrics={"coverage": coverage},
            )
        )
    if "SPY" in prices.columns and coverage > 0:
        port = holdings_backtest(weights / coverage, prices).iloc[-252:]
        spy = prices["SPY"].pct_change(fill_method=None).reindex(port.index)
        beta = metrics.beta(port, spy)
        if math.isfinite(beta) and beta > limits.high_beta:
            ideas.append(
                Idea(
                    kind="portfolio",
                    severity="consider",
                    title=f"Beta {beta:.2f} to the S&P 500",
                    summary=(
                        "Over the last year your priced holdings moved more than the market; a "
                        "10% market drop has historically meant roughly "
                        f"{beta * 10:.0f}% for them."
                    ),
                    rationale=[f"Measured on {len(port)} trading days of current weights"],
                    score=beta,
                    metrics={"beta": beta},
                )
            )
    return ideas


def _strategy_ideas(table: pd.DataFrame, prices: pd.DataFrame, limits: Limits) -> list[Idea]:
    ideas: list[Idea] = []
    weights = priced_weights(table, set(prices.columns))
    weights = weights[weights > 0]
    if len(weights) and weights.sum() > 0:
        held = prices[list(weights.index)].dropna(how="all")
        w = weights / weights.sum()
        if len(held) > 300:
            overlay = ma_timing(held, weights=w, cost_bps=5.0)
            if not overlay.returns.empty:
                hold = equal_weight_monthly(
                    held, weights=w, cost_bps=5.0, start_after=overlay.signals.index[9]
                )
                common = overlay.returns.index.intersection(hold.returns.index)
                o, h = overlay.returns.loc[common], hold.returns.loc[common]
                dd_gain = metrics.max_drawdown(o) - metrics.max_drawdown(h)
                cagr_cost = metrics.cagr(h) - metrics.cagr(o)
                good = dd_gain >= limits.overlay_min_dd_improvement and (
                    cagr_cost <= limits.overlay_max_cagr_cost
                )
                ideas.append(
                    Idea(
                        kind="strategy",
                        severity="consider" if good else "info",
                        title="10-month MA timing on your current mix",
                        summary=(
                            "Strategy 1 as an overlay: each holding goes to cash while it's "
                            "below its 10-month average. "
                            + (
                                "It would have cut the worst drawdown without giving up much."
                                if good
                                else "Historically it didn't clearly beat holding this mix."
                            )
                        ),
                        rationale=[
                            f"Max drawdown {metrics.max_drawdown(o):.1%} vs "
                            f"{metrics.max_drawdown(h):.1%} holding",
                            f"CAGR {metrics.cagr(o):.1%} vs {metrics.cagr(h):.1%}",
                            f"Sharpe {metrics.sharpe_ratio(o):.2f} vs "
                            f"{metrics.sharpe_ratio(h):.2f}",
                            f"{common[0].date()} to {common[-1].date()}, 5 bps costs, "
                            "trades the day after each month-end signal",
                        ],
                        symbols=list(w.index),
                        score=float(dd_gain),
                        metrics={"dd_improvement": float(dd_gain), "cagr_cost": float(cagr_cost)},
                    )
                )
    classes = table.groupby("asset_class")["weight"].sum()
    if float(classes.get("US Equity", 0.0)) > limits.max_us_equity and all(
        s in prices.columns for s in GTAA
    ):
        gtaa = prices[list(GTAA)].dropna()
        if len(gtaa) > 300:
            timed = ma_timing(gtaa, cost_bps=5.0)
            spy = prices["SPY"].pct_change(fill_method=None).reindex(timed.returns.index)
            corr = float(timed.returns.corr(spy))
            ideas.append(
                Idea(
                    kind="strategy",
                    severity="consider",
                    title="Faber GTAA as a diversifier",
                    summary=(
                        "Five asset classes, each timed with the 10-month rule. It targets "
                        "smaller drawdowns than an all-equity portfolio."
                    ),
                    rationale=[
                        f"CAGR {metrics.cagr(timed.returns):.1%}, max drawdown "
                        f"{metrics.max_drawdown(timed.returns):.1%}",
                        f"Correlation to SPY {corr:.2f}",
                        "Spec: docs/strategies/01-ma-timing.md",
                    ],
                    symbols=list(GTAA),
                    score=1 - corr if math.isfinite(corr) else 0.0,
                    metrics={"correlation_to_spy": corr},
                )
            )
    return ideas


def _candidate_ideas(
    table: pd.DataFrame,
    prices: pd.DataFrame,
    signals: pd.DataFrame,
    classifier: Classifier,
    limits: Limits,
) -> list[Idea]:
    if signals.empty:
        return []
    held = set(table["symbol"]) if not table.empty else set()
    pool = signals[
        (signals["history_days"] >= limits.min_history_days)
        & signals["above_10m_sma"].map(lambda v: _flag(v) is True)
        & (signals["momentum_12_1"] > 0)
        & ~signals.index.isin(list(held))
    ].copy()
    if pool.empty:
        return []
    universe_mom = signals["momentum_12_1"].dropna()
    pool["momentum_pct"] = [float((universe_mom < m).mean()) for m in pool["momentum_12_1"]]

    weights = priced_weights(table, set(prices.columns)) if not table.empty else pd.Series()
    port = (
        holdings_backtest(weights / weights.sum(), prices).iloc[-252:]
        if len(weights) and weights.sum() > 0
        else None
    )
    rets = prices.pct_change(fill_method=None)
    sector_weights = table.groupby("sector")["weight"].sum() if not table.empty else pd.Series()

    scored = []
    for symbol, s in pool.iterrows():
        cls = classifier.classify(str(symbol), "stock")
        corr = float(rets[symbol].reindex(port.index).corr(port)) if port is not None else math.nan
        light = float(sector_weights.get(cls.sector, 0.0)) < 0.10
        div = 1 - corr if math.isfinite(corr) else 0.5
        score = 0.5 * float(s["momentum_pct"]) + 0.3 * div + 0.2 * float(light)
        scored.append((score, str(symbol), s, cls, corr, light))
    scored.sort(key=lambda x: -x[0])

    ideas = []
    for score, symbol, s, cls, corr, light in scored[: limits.candidates]:
        rationale = [
            f"12-1 momentum {s['momentum_12_1']:+.0%} (beats {s['momentum_pct']:.0%} of the "
            "universe)",
            f"Above its 10-month average ({s['month_end_close']:.2f} vs {s['sma_10m']:.2f})",
        ]
        if math.isfinite(corr):
            rationale.append(f"Correlation to your portfolio {corr:.2f} over the last year")
        if light:
            rationale.append(f"{cls.sector}: under 10% of your portfolio")
        rationale.append(f"63-day volatility {s['vol_63d']:.0%} annualized")
        ideas.append(
            Idea(
                kind="candidate",
                severity="info",
                title=f"{symbol}: uptrend that would {'diversify' if light else 'add to'} you",
                summary=f"{cls.sector}. Ranked by momentum, diversification and sector gaps.",
                rationale=rationale,
                symbols=[symbol],
                score=float(score),
                metrics={
                    "momentum_12_1": float(s["momentum_12_1"]),
                    "correlation": corr,
                    "score": float(score),
                },
            )
        )
    return ideas


def _flag(value: object) -> bool | None:
    """Normalise a maybe-missing boolean (Python, NumPy or NaN) to True/False/None."""
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return None
    return bool(value)


def ideas_from_lake(
    lake: Lake, classifier: Classifier, limits: Limits | None = None
) -> IdeasReport:
    """Latest synced portfolio + clean bars in, ideas out."""
    table = holdings_table(latest_snapshot(lake), classifier)
    bars = load_bars(lake)
    prices = close_matrix(bars) if not bars.empty else pd.DataFrame()
    return generate_ideas(table, prices, classifier, limits=limits)
